=== zono32/Dual_2/03 LENGUAJES/eval_01/practicas/XML_XSD_actividades/XML_XSD_actividadesPlatega/pag_24_claves.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empregado" type="tipoEmpregado" maxOccurs="200"/>
        <xs:element name="departamento" type="tipoDepartamento" maxOccurs="8"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="depUnico">
      <xs:selector xpath="departamento"/>
      <xs:field xpath="@codigo"/>
    </xs:key>
    <xs:keyref name="departamento" refer="depUnico">
      <xs:selector xpath="empregado"/>
      <xs:field xpath="departamento"/>
    </xs:keyref>
  </xs:element>
  
  <xs:complexType name="tipoEmpregado">
    <xs:sequence>
      <xs:element name="nome" type="xs:string"/>
      <xs:element name="departamento" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoDepartamento">
    <xs:sequence>
      <xs:element name="nome" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="codigo" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== zono32/Dual_2/03 LENGUAJES/eval_01/practicas/XML_XSD_actividades/XML_XSD_actividadesPlatega/pag_24_claves.xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                    xsi:noNamespaceSchemaLocation="pag_24_claves.xsd">
  <empregado>
    <nome>Iria</nome>
    <departamento>IFC</departamento>
  </empregado>
  <empregado>
    <nome>Xoel</nome>
    <departamento>CON</departamento>
  </empregado>
    <!-- ejemplar empregado para experimentar la validez 
      <empregado>
    <nome>Oscar</nome>
    <departamento>FOL</departamento>
  </empregado>
   -->

  <departamento codigo="IFC">
    <nome>Informática</nome>
  </departamento>
  <departamento codigo="CON">
    <nome>Contabilidade</nome>
  </departamento>
  
  <!-- ejemplar departamento para experimentar la validez 
    <departamento codigo="IP">
    <nome>Imaxe Persoal</nome>
  </departamento>
  -->
</empresa>
