=== zono32/Dual_2/03 LENGUAJES/eval_01/practicas/linguaxeXM_actividadesValidacionConDTD/Tarefa6a_sol_bis.dtd
<!ELEMENT reservas (reserva*, cliente*)>
<!ELEMENT reserva (data_inicio, data_fin)>
<!ATTLIST reserva
	   cliente IDREF #REQUIRED
	   tipo (SA | AD | MP |PC | TI) #REQUIRED
	   habitación (Individual | Dobre) #REQUIRED>
<!ELEMENT data_inicio (observacións?)>
<!ELEMENT data_fin (observacións?)>
<!ENTITY % data 
	   "ano CDATA #REQUIRED
	    mes (Xaneiro | Febreiro | Marzo | Abril | Maio | Xuño | Xullo | 
         Agosto | Setembro | Outubro | Novembro | Decembro) #REQUIRED
	    día CDATA #REQUIRED">
<!ATTLIST data_inicio %data; >	
<!ATTLIST data_fin %data; > 
<!ELEMENT observacións (#PCDATA)>	
	
<!ELEMENT cliente (nome, apelidos, mobil, correo?)>
<!ATTLIST cliente
     id ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT apelidos (#PCDATA)>
<!ELEMENT mobil (#PCDATA)>
<!ELEMENT correo (#PCDATA)>

=== zono32/Dual_2/03 LENGUAJES/eval_01/practicas/linguaxeXM_actividadesValidacionConDTD/Tarefa6a_sol_bis.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE reservas SYSTEM "Tarefa6a_sol_bis.dtd">
<reservas>
	<reserva cliente="CLI1" tipo="AD" habitación="Dobre">
		<data_inicio ano="2013" mes="Febreiro" día="5" >
		<observacións>Chegan sobre as 23:30</observacións>
		</data_inicio>
		<data_fin ano="2013" mes="Febreiro" día="9" />
		
	</reserva>
	<reserva cliente="CLI2" tipo="MP" habitación="Individual">
		<data_inicio ano="2013" mes="Febreiro" día="7" />
		<data_fin ano="2013" mes="Febreiro" día="15">
		<observacións>Saída as 16:00</observacións>
		</data_fin>
	</reserva>	
	<reserva cliente="CLI1" tipo="PC" habitación="Dobre">
		<data_inicio ano="2013" mes="Febreiro" día="18" />
		<data_fin ano="2013" mes="Febreiro" día="23" />
	</reserva>	
	<cliente id="CLI1">
		<nome>Eva</nome>
		<apelidos>Sobral García</apelidos>
		<mobil>688998899</mobil>
		<correo>eva.sobral@meucorreo.com</correo>
	</cliente>
	<cliente id="CLI2">
		<nome>Xan</nome>
		<apelidos>López Paz</apelidos>
		<mobil>677778899</mobil>
	</cliente>
</reservas>
