<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE mensaxe [
<!ELEMENT mensaxe (de , para+ , asunto , corpo? , adxunto*)>
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT corpo (#PCDATA)>
<!ELEMENT adxunto (#PCDATA)>
]>
<mensaxe>
   <de>maria@gmail.com</de>
   <para>ignacio@mail.com</para>
   <para>maria@mail.com</para>
   <para>marta@mail.com</para>
   <asunto>Envíoche os arquivos</asunto>
   <adxunto>D:\fotos\naCea.jpg</adxunto>
   <adxunto>D:\fotos\naPraia.jpg</adxunto>
  
</mensaxe>
