<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reservas [
<!ELEMENT reservas (reserva*)>
 <!ATTLIST reservas ano CDATA #REQUIRED>
 <!ELEMENT reserva (data, evento?, (clienteEmpresa | clientePersonal))>
 <!ELEMENT reserva(data) EMPTY>
 <!ELEMENT evento (#PCDATA)>
 <!ELEMENT clienteEmpresa (#PCDATA)>
 <!ELEMENT clientePersonal (#PCDATA)>
 <!ATTLIST reserva  local (polideportivo | local_social)#REQUIRED
 bonificacion  CDATA #IMPLIED>
 <!ATTLIST data 
 mes CDATA #REQUIRED
 dia CDATA #REQUIRED
 horario (mañá | tarde| dia)"tarde">

]>
<reservas ano="2017" >
<reserva>
<data>localsocial</data>
<evento>cumple </evento>
<clientePersonal>yo</clientePersonal>
</reserva>
</reservas>

