<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
  <!ELEMENT paises (pais*)>
  <!ELEMENT pais (nome, continente, G20?, oceano*)>
  <!ELEMENT nome (#PCDATA)>
   <!ELEMENT continente (#PCDATA)>
  <!ELEMENT G20 EMPTY>
  <!ELEMENT oceano (#PCDATA)>
]>

<paises>
  <pais>
    <nome>Sudáfrica</nome>
    <continente>Africa</continente>
    <G20 />
    <oceano>Atlántico</oceano>
    <oceano>Indico</oceano>
  </pais>
  <pais>
     <nome>Colombia</nome>
    <continente>América</continente>
    <oceano>Atlántico</oceano>
    <oceano>Pacífico</oceano>
  </pais>
  <pais>
     <nome>Bolivia</nome>
    <continente>América</continente>
  </pais>
  <pais>
    <nome>India</nome>
    <continente>Asia</continente>
    <G20 />
    <oceano>Indico</oceano>
 </pais>
</paises> 


